kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:resource-usage-collect:agent
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes","configmaps", "pods", "events" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete","deletecollection", "patch" ]
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "create", "get", "list", "update", "watch", "patch" ]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores" ]
    verbs: [ "get", "list", "watch", "create", "update", "delete","deletecollection", "patch" ]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores/status" ]
    verbs: [ "update", "patch" ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: open-cluster-management-addon-manager-resource-usage-collect
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:resource-usage-collect:agent
subjects:
  - kind: ServiceAccount
    name: addon-manager-controller-sa
    namespace: open-cluster-management-hub
