apiVersion: cluster.open-cluster-management.io/v1beta2
kind: ManagedClusterSetBinding
metadata:
  generation: 1
  name: global
  namespace: default
spec:
  clusterSet: global

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: placement-all
  namespace: default
spec:
  clusterSets:
    - global