apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: addon-manager
  namespace: open-cluster-management-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: addon-manager
subjects:
- kind: ServiceAccount
  name: addon-manager-controller-sa
