// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// DeviceListerExpansion allows custom methods to be added to
// DeviceLister.
type DeviceListerExpansion interface{}

// DeviceNamespaceListerExpansion allows custom methods to be added to
// DeviceNamespaceLister.
type DeviceNamespaceListerExpansion interface{}

// DeviceAddOnConfigListerExpansion allows custom methods to be added to
// DeviceAddOnConfigLister.
type DeviceAddOnConfigListerExpansion interface{}

// DeviceAddOnConfigNamespaceListerExpansion allows custom methods to be added to
// DeviceAddOnConfigNamespaceLister.
type DeviceAddOnConfigNamespaceListerExpansion interface{}

// DriverListerExpansion allows custom methods to be added to
// DriverLister.
type DriverListerExpansion interface{}

// DriverNamespaceListerExpansion allows custom methods to be added to
// DriverNamespaceLister.
type DriverNamespaceListerExpansion interface{}
