// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	apisv1alpha1 "open-cluster-management-io/addon-contrib/device-addon/pkg/apis/v1alpha1"
	versioned "open-cluster-management-io/addon-contrib/device-addon/pkg/client/clientset/versioned"
	internalinterfaces "open-cluster-management-io/addon-contrib/device-addon/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "open-cluster-management-io/addon-contrib/device-addon/pkg/client/listers/apis/v1alpha1"
	time "time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// DeviceAddOnConfigInformer provides access to a shared informer and lister for
// DeviceAddOnConfigs.
type DeviceAddOnConfigInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.DeviceAddOnConfigLister
}

type deviceAddOnConfigInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewDeviceAddOnConfigInformer constructs a new informer for DeviceAddOnConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewDeviceAddOnConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredDeviceAddOnConfigInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredDeviceAddOnConfigInformer constructs a new informer for DeviceAddOnConfig type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredDeviceAddOnConfigInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().DeviceAddOnConfigs(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.EdgeV1alpha1().DeviceAddOnConfigs(namespace).Watch(context.TODO(), options)
			},
		},
		&apisv1alpha1.DeviceAddOnConfig{},
		resyncPeriod,
		indexers,
	)
}

func (f *deviceAddOnConfigInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredDeviceAddOnConfigInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *deviceAddOnConfigInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&apisv1alpha1.DeviceAddOnConfig{}, f.defaultInformer)
}

func (f *deviceAddOnConfigInformer) Lister() v1alpha1.DeviceAddOnConfigLister {
	return v1alpha1.NewDeviceAddOnConfigLister(f.Informer().GetIndexer())
}
