apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{name}}
  namespace: {{namespace}}
  labels:
    "dynamic-scoring-framework-mcp/generated": "true"
spec:
  numberOfClusters: 1
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchLabels:
            cluster-name: {{cluster_name}}
