apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  annotations:
    addon.open-cluster-management.io/lifecycle: addon-manager
  name: fluid
spec:
  addOnConfiguration: {}
  addOnMeta:
    displayName: Fluid
    description: Fluid is an open source Kubernetes-native Distributed Dataset Orchestrator and Accelerator for data-intensive applications, such as big data and AI applications.
  installStrategy:
    type: Manual
  supportedConfigs:
  - defaultConfig:
      name: fluid-0.0.1
    group: addon.open-cluster-management.io
    resource: addontemplates
