global:
  imageOverrides:
    agentPrincipalImage: quay.io/mikeshng/argocd-agent-principal:latest
    agentAgentImage: quay.io/mikeshng/argocd-agent-agent:latest
  imagePullPolicy: IfNotPresent

agent:
  mode: "managed" # must be 'managed' or 'autonomous'
  secrets:
    cacrt: ""
    cakey: ""
    tlscrt: ""
    tlskey: ""
    jwtkey: ""
  principal:
    server:
      address: ""
      port: 443
