apiVersion: batch/v1
kind: Job
metadata:
  name: gpu-dummy-job
  namespace: default
spec:
  parallelism: 1
  completions: 1
  suspend: false
  template:
    spec:
      tolerations:
        - key: "nvidia.com/gpu"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: dummy-job
          image: gcr.io/k8s-staging-perf-tests/sleep:v0.0.3
          args: ["60s"]
          resources:
            requests:
              cpu: "100m"
              memory: "100Mi"
              nvidia.com/gpu: "5"
            limits:
              cpu: "100m"
              memory: "100Mi"
              nvidia.com/gpu: "5"
      restartPolicy: Never
