apiVersion: addon.open-cluster-management.io/v1alpha1
kind: AddOnTemplate
metadata:
  name: kueue-addon-{{ .Chart.Version }}
spec:
  addonName: kueue-addon
  agentSpec:
    workload:
      manifests:
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: kueue-resourceflavor-ocm-rolebinding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: kueue-resourceflavor-editor-role
          subjects:
          - kind: ServiceAccount
            name: klusterlet-work-sa
            namespace: open-cluster-management-agent
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: kueue-clusterqueue-ocm-rolebinding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: kueue-clusterqueue-editor-role
          subjects:
          - kind: ServiceAccount
            name: klusterlet-work-sa
            namespace: open-cluster-management-agent
        - apiVersion: rbac.authorization.k8s.io/v1
          kind: ClusterRoleBinding
          metadata:
            name: kueue-localqueue-ocm-rolebinding
          roleRef:
            apiGroup: rbac.authorization.k8s.io
            kind: ClusterRole
            name: kueue-localqueue-editor-role
          subjects:
          - kind: ServiceAccount
            name: klusterlet-work-sa
            namespace: open-cluster-management-agent
        - apiVersion: kueue.x-k8s.io/v1beta1
          kind: ResourceFlavor
          metadata:
            name: {{ .Values.resourceFlavor.name}}
        - apiVersion: kueue.x-k8s.io/v1beta1
          kind: ClusterQueue
          metadata:
            name: {{ .Values.clusterQueue.name}}
          spec:
            namespaceSelector: {{ .Values.clusterQueue.namespaceSelector  }}
            resourceGroups: 
            {{- toYaml .Values.clusterQueue.resourceGroups | nindent 12 }}
        - apiVersion: kueue.x-k8s.io/v1beta1
          kind: LocalQueue
          metadata:
            namespace: {{ .Values.localQueue.namespace}}
            name: {{ .Values.localQueue.name}}
          spec:
            clusterQueue: {{ .Values.clusterQueue.name}}
