apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: kueue-addon
spec:
  addOnMeta:
    displayName: kueue-addon
    description: kueue-addon
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addontemplates
  installStrategy:
    type: Placements
    placements:
    - name: {{ .Values.placement.name }}
      namespace: {{ .Release.Namespace }}
      configs:
      - name: kueue-addon-{{ .Chart.Version }}
        group: addon.open-cluster-management.io
        resource: addontemplates
