kind: Deployment
apiVersion: apps/v1
metadata:
  name: kueue-addon-controller
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kueue-addon-controller
  template:
    metadata:
      labels:
        app: kueue-addon-controller
    spec:
      serviceAccount: kueue-addon-controller-sa
      containers:
        - name: kueue-addon-controller
          image: {{ .Values.image.repository }}:{{ .Values.image.tag | default (print "v" .Chart.Version) }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "/kueue-addon-controller"
            - "hub"
          env:
            - name: KUEUE_NAMESPACE
              value: {{ .Values.kueue.namespace }}
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: SERVICE_ACCOUNT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            {{- if .Values.clusterProxy.url }}
            - name: CLUSTER_PROXY_URL
              value: {{ .Values.clusterProxy.url }}
            {{- end }}
            {{- if .Values.clusterProxy.impersonation.enabled }}
            - name: CLUSTER_PROXY_IMPERSONATION_ENABLED
              value: "true"
            {{- end }}

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: kueue-addon-controller-sa
  namespace: {{ .Release.Namespace }}