apiVersion: v1
kind: Secret
metadata:
  name: argocd-agent-tls
  namespace: argocd
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.agent.secrets.tlscrt | b64enc | quote }}
  tls.key: {{ .Values.agent.secrets.tlskey | b64enc | quote }}
