apiVersion: v1
kind: Secret
metadata:
  name: argocd-agent-ca
  namespace: open-cluster-management-hub
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.agent.secrets.cacrt | b64enc | quote }}
  tls.key: {{ .Values.agent.secrets.cakey | b64enc | quote }}
