//go:build !ignore_autogenerated

/*
Copyright 2025.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
	"open-cluster-management.io/dynamic-scoring/pkg/common"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthConfig) DeepCopyInto(out *AuthConfig) {
	*out = *in
	out.TokenSecretRef = in.TokenSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthConfig.
func (in *AuthConfig) DeepCopy() *AuthConfig {
	if in == nil {
		return nil
	}
	out := new(AuthConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScorer) DeepCopyInto(out *DynamicScorer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScorer.
func (in *DynamicScorer) DeepCopy() *DynamicScorer {
	if in == nil {
		return nil
	}
	out := new(DynamicScorer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicScorer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScorerList) DeepCopyInto(out *DynamicScorerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicScorer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScorerList.
func (in *DynamicScorerList) DeepCopy() *DynamicScorerList {
	if in == nil {
		return nil
	}
	out := new(DynamicScorerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicScorerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScorerSpec) DeepCopyInto(out *DynamicScorerSpec) {
	*out = *in
	in.Source.DeepCopyInto(&out.Source)
	in.Scoring.DeepCopyInto(&out.Scoring)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScorerSpec.
func (in *DynamicScorerSpec) DeepCopy() *DynamicScorerSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicScorerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScorerStatus) DeepCopyInto(out *DynamicScorerStatus) {
	*out = *in
	if in.LastSyncedConfig != nil {
		in, out := &in.LastSyncedConfig, &out.LastSyncedConfig
		*out = new(common.Config)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScorerStatus.
func (in *DynamicScorerStatus) DeepCopy() *DynamicScorerStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicScorerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScoringConfig) DeepCopyInto(out *DynamicScoringConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScoringConfig.
func (in *DynamicScoringConfig) DeepCopy() *DynamicScoringConfig {
	if in == nil {
		return nil
	}
	out := new(DynamicScoringConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicScoringConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScoringConfigList) DeepCopyInto(out *DynamicScoringConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]DynamicScoringConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScoringConfigList.
func (in *DynamicScoringConfigList) DeepCopy() *DynamicScoringConfigList {
	if in == nil {
		return nil
	}
	out := new(DynamicScoringConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *DynamicScoringConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScoringConfigSpec) DeepCopyInto(out *DynamicScoringConfigSpec) {
	*out = *in
	if in.Masks != nil {
		in, out := &in.Masks, &out.Masks
		*out = make([]common.Mask, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScoringConfigSpec.
func (in *DynamicScoringConfigSpec) DeepCopy() *DynamicScoringConfigSpec {
	if in == nil {
		return nil
	}
	out := new(DynamicScoringConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DynamicScoringConfigStatus) DeepCopyInto(out *DynamicScoringConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DynamicScoringConfigStatus.
func (in *DynamicScoringConfigStatus) DeepCopy() *DynamicScoringConfigStatus {
	if in == nil {
		return nil
	}
	out := new(DynamicScoringConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScoringConfigWithAuth) DeepCopyInto(out *ScoringConfigWithAuth) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(common.ScoringParams)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScoringConfigWithAuth.
func (in *ScoringConfigWithAuth) DeepCopy() *ScoringConfigWithAuth {
	if in == nil {
		return nil
	}
	out := new(ScoringConfigWithAuth)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretRef) DeepCopyInto(out *SecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretRef.
func (in *SecretRef) DeepCopy() *SecretRef {
	if in == nil {
		return nil
	}
	out := new(SecretRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceConfigWithAuth) DeepCopyInto(out *SourceConfigWithAuth) {
	*out = *in
	if in.Params != nil {
		in, out := &in.Params, &out.Params
		*out = new(common.SourceParams)
		**out = **in
	}
	if in.Auth != nil {
		in, out := &in.Auth, &out.Auth
		*out = new(AuthConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceConfigWithAuth.
func (in *SourceConfigWithAuth) DeepCopy() *SourceConfigWithAuth {
	if in == nil {
		return nil
	}
	out := new(SourceConfigWithAuth)
	in.DeepCopyInto(out)
	return out
}
