apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: {{ .Values.addon.name }}
spec:
  addOnMeta:
    displayName: {{ .Values.addon.displayName }}
  supportedConfigs:
    - group: addon.open-cluster-management.io
      resource: addontemplates
      defaultConfig:
        name: resource-usage-collect-{{ .Chart.Version }}
  installStrategy:
    type: Placements
    placements:
      - name: {{ .Values.addon.name }}-global
        namespace: {{ .Release.Namespace }}



