apiVersion: federation-ai.open-cluster-management.io/v1alpha1
kind: FederatedLearning
metadata:
  name: federated-learning-sample
spec:
  framework: flower
  server:
    image: quay.io/open-cluster-management/flower-app:cifar10-v1.0.0
    minAvailableClients: 2
    # superlink: superlink.flower-system:9091  # default, can be omitted
  client:
    image: quay.io/open-cluster-management/flower-app:cifar10-v1.0.0
    # supernode: flower-supernode.flower-addon:9094  # default, can be omitted
    placement:
      clusterSets:
        - global
      predicates:
        - requiredClusterSelector:
            labelSelector:
              matchLabels:
                feature.open-cluster-management.io/addon-flower-addon: available
