// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "open-cluster-management-io/addon-contrib/device-addon/pkg/apis/v1alpha1"
	scheme "open-cluster-management-io/addon-contrib/device-addon/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DeviceAddOnConfigsGetter has a method to return a DeviceAddOnConfigInterface.
// A group's client should implement this interface.
type DeviceAddOnConfigsGetter interface {
	DeviceAddOnConfigs(namespace string) DeviceAddOnConfigInterface
}

// DeviceAddOnConfigInterface has methods to work with DeviceAddOnConfig resources.
type DeviceAddOnConfigInterface interface {
	Create(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.CreateOptions) (*v1alpha1.DeviceAddOnConfig, error)
	Update(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.UpdateOptions) (*v1alpha1.DeviceAddOnConfig, error)
	UpdateStatus(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.UpdateOptions) (*v1alpha1.DeviceAddOnConfig, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.DeviceAddOnConfig, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DeviceAddOnConfigList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DeviceAddOnConfig, err error)
	DeviceAddOnConfigExpansion
}

// deviceAddOnConfigs implements DeviceAddOnConfigInterface
type deviceAddOnConfigs struct {
	client rest.Interface
	ns     string
}

// newDeviceAddOnConfigs returns a DeviceAddOnConfigs
func newDeviceAddOnConfigs(c *EdgeV1alpha1Client, namespace string) *deviceAddOnConfigs {
	return &deviceAddOnConfigs{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the deviceAddOnConfig, and returns the corresponding deviceAddOnConfig object, and an error if there is any.
func (c *deviceAddOnConfigs) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.DeviceAddOnConfig, err error) {
	result = &v1alpha1.DeviceAddOnConfig{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of DeviceAddOnConfigs that match those selectors.
func (c *deviceAddOnConfigs) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DeviceAddOnConfigList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DeviceAddOnConfigList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested deviceAddOnConfigs.
func (c *deviceAddOnConfigs) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a deviceAddOnConfig and creates it.  Returns the server's representation of the deviceAddOnConfig, and an error, if there is any.
func (c *deviceAddOnConfigs) Create(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.CreateOptions) (result *v1alpha1.DeviceAddOnConfig, err error) {
	result = &v1alpha1.DeviceAddOnConfig{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceAddOnConfig).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a deviceAddOnConfig and updates it. Returns the server's representation of the deviceAddOnConfig, and an error, if there is any.
func (c *deviceAddOnConfigs) Update(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.UpdateOptions) (result *v1alpha1.DeviceAddOnConfig, err error) {
	result = &v1alpha1.DeviceAddOnConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		Name(deviceAddOnConfig.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceAddOnConfig).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *deviceAddOnConfigs) UpdateStatus(ctx context.Context, deviceAddOnConfig *v1alpha1.DeviceAddOnConfig, opts v1.UpdateOptions) (result *v1alpha1.DeviceAddOnConfig, err error) {
	result = &v1alpha1.DeviceAddOnConfig{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		Name(deviceAddOnConfig.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(deviceAddOnConfig).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the deviceAddOnConfig and deletes it. Returns an error if one occurs.
func (c *deviceAddOnConfigs) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *deviceAddOnConfigs) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched deviceAddOnConfig.
func (c *deviceAddOnConfigs) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.DeviceAddOnConfig, err error) {
	result = &v1alpha1.DeviceAddOnConfig{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("deviceaddonconfigs").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
