// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	v1alpha1 "open-cluster-management-io/addon-contrib/device-addon/pkg/apis/v1alpha1"
	scheme "open-cluster-management-io/addon-contrib/device-addon/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// DriversGetter has a method to return a DriverInterface.
// A group's client should implement this interface.
type DriversGetter interface {
	Drivers(namespace string) DriverInterface
}

// DriverInterface has methods to work with Driver resources.
type DriverInterface interface {
	Create(ctx context.Context, driver *v1alpha1.Driver, opts v1.CreateOptions) (*v1alpha1.Driver, error)
	Update(ctx context.Context, driver *v1alpha1.Driver, opts v1.UpdateOptions) (*v1alpha1.Driver, error)
	UpdateStatus(ctx context.Context, driver *v1alpha1.Driver, opts v1.UpdateOptions) (*v1alpha1.Driver, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.Driver, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.DriverList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Driver, err error)
	DriverExpansion
}

// drivers implements DriverInterface
type drivers struct {
	client rest.Interface
	ns     string
}

// newDrivers returns a Drivers
func newDrivers(c *EdgeV1alpha1Client, namespace string) *drivers {
	return &drivers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the driver, and returns the corresponding driver object, and an error if there is any.
func (c *drivers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Drivers that match those selectors.
func (c *drivers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.DriverList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.DriverList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested drivers.
func (c *drivers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a driver and creates it.  Returns the server's representation of the driver, and an error, if there is any.
func (c *drivers) Create(ctx context.Context, driver *v1alpha1.Driver, opts v1.CreateOptions) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(driver).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a driver and updates it. Returns the server's representation of the driver, and an error, if there is any.
func (c *drivers) Update(ctx context.Context, driver *v1alpha1.Driver, opts v1.UpdateOptions) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivers").
		Name(driver.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(driver).
		Do(ctx).
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *drivers) UpdateStatus(ctx context.Context, driver *v1alpha1.Driver, opts v1.UpdateOptions) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("drivers").
		Name(driver.Name).
		SubResource("status").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(driver).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the driver and deletes it. Returns an error if one occurs.
func (c *drivers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivers").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *drivers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("drivers").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched driver.
func (c *drivers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.Driver, err error) {
	result = &v1alpha1.Driver{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("drivers").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
