apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: {{ .Values.placement.name }}
  namespace: {{ .Values.placement.namespace }}
spec:
  clusterSets:
    - global

