kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:device-addon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:device-addon
subjects:
  - kind: ServiceAccount
    name: device-addon-sa
    namespace: open-cluster-management