apiVersion: apps/v1
kind: Deployment
metadata:
  name: device-addon-manager
  namespace: open-cluster-management
spec:
  replicas: 1
  selector:
    matchLabels:
      open-cluster-management.io/addon: device
  template:
    metadata:
      labels:
        open-cluster-management.io/addon: device
    spec:
      serviceAccount: device-addon-sa
      containers:
        - name: manager
          image: quay.io/skeeey/device-addon:latest
          imagePullPolicy: IfNotPresent
          args:
          - "/device-addon"
          - "manager"
