kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: open-cluster-management:resource-usage-collect:agent
  namespace: {{ .ClusterName }}
rules:
  - apiGroups: [""]
    resources: ["nodes","configmaps", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["addonplacementscores"]
    verbs: ["get", "list", "watch", "create", "update", "delete", "deletecollection", "patch"]
  - apiGroups: [ "cluster.open-cluster-management.io" ]
    resources: [ "addonplacementscores/status" ]
    verbs: [ "update", "patch" ]

