apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ClusterManagementAddOn
metadata:
  name: kueue-addon
spec:
  addOnMeta:
    displayName: kueue-addon
  supportedConfigs:
  - group: addon.open-cluster-management.io
    resource: addontemplates
  installStrategy:
    type: Placements
    placements:
    - name: hub
      namespace: open-cluster-management-addon
      configs:
      - name: kueue-addon-hub
        group: addon.open-cluster-management.io
        resource: addontemplates
    - name: spoke
      namespace: open-cluster-management-addon
      configs:
      - name: kueue-addon-spoke
        group: addon.open-cluster-management.io
        resource: addontemplates
