kind: Deployment
apiVersion: apps/v1
metadata:
  name: kueue-addon-controller
  namespace: open-cluster-management-addon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kueue-addon-controller
  template:
    metadata:
      labels:
        app: kueue-addon-controller
    spec:
      serviceAccount: kueue-addon-controller-sa
      containers:
        - name: kueue-addon-controller
          image: kueue-addon-image
          imagePullPolicy: Always
          args:
            - "/kueue-addon-controller"
            - "hub"
          env:
            - name: KUEUE_NAMESPACE
              value: kueue-system

---

kind: ServiceAccount
apiVersion: v1
metadata:
  name: kueue-addon-controller-sa
  namespace: open-cluster-management-addon