{{ if .Values.opentelemetryCollector.tls.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: otel-addon-manager
  namespace: open-cluster-management-hub
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["otel-signer"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: otel-addon-manager
  namespace: open-cluster-management-hub
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: otel-addon-manager
subjects:
- kind: ServiceAccount
  name: addon-manager-controller-sa
{{ end }}
