apiVersion: dynamic-scoring.open-cluster-management.io/v1alpha1
kind: DynamicScorer
metadata:
  name: ai-workload-power-scorer
spec:
  description: |
    This score evaluates whether there is sufficient power headroom based on the cluster’s predicted power consumption and information about applications and devices.
    The score ranges from 0 to 100, where values closer to 0 indicate little to no available power headroom. 
  configURL: http://${AI_WORKLOAD_SCORER_HOST}/power/config
  configSyncMode: Full
  location: External
  scoreDestination: AddOnPlacementScore
  scoreDimensionFormat: "${app};${device}"
  source:
    auth:
      tokenSecretRef:
        name: source-query-secret
        key: token