apiVersion: dynamic-scoring.open-cluster-management.io/v1
kind: DynamicScorer
metadata:
  name: example-performance-scorer
  namespace: dynamic-scoring
spec:
  description: An example performance scorer for applications and devices
  configURL: http://static-scorer:8000/performance/config
  configSyncMode: Full
  location: Internal
  scoreDestination: AddOnPlacementScore
  scoreDimensionFormat: "${app};${device}"
