apiVersion: dynamic-scoring.open-cluster-management.io/v1
kind: DynamicScorer
metadata:
  name: llm-forecast-scorer
  namespace: dynamic-scoring
spec:
  description: A sample llm forecast scorer for time series data
  configURL:  http://${EXTERNAL_SCORER_IP}:8000/config
  configSyncMode: Full
  location: External
  scoreDestination: AddOnPlacementScore
  scoreDimensionFormat: "${node};${namespace};${pod}"
  source:
    host: http://kube-prometheus-kube-prome-prometheus.monitoring.svc:9090
    path: /api/v1/query_range
    params:
      query: sum by (node, namespace, pod) (rate(container_cpu_usage_seconds_total{container!="", pod!=""}[1m]))
      range: 3600
      step: 60
    # auth:
    #   tokenSecretRef:
    #     name: prometheus-token-secret
    #     key: token
  scoring:
    host:  http://${EXTERNAL_SCORER_IP}:8000
    path: /scoring
    params:
      name: llm_forecast_score
      interval: 60
    auth:
      tokenSecretRef:
        name: api-auth-secret 
        key: token
