# The following workflow is to handle skipped but required jobs when only documentations is changed.
# Github doc: https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/troubleshooting-required-status-checks#handling-skipped-but-required-checks
name: kueue-addon-post

on:
  push:
    paths:
      - 'kueue-addon/**'
    branches:
      - main
  workflow_dispatch: {}

env:
  # Common versions
  GO_VERSION: '1.23'
  GO_REQUIRED_MIN_VERSION: ''

permissions:
  contents: read

jobs:
  images:
    name: images
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: install Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: install imagebuilder
        run: go install github.com/openshift/imagebuilder/cmd/imagebuilder@v1.2.3
      - name: pull base image
        run: docker pull registry.access.redhat.com/ubi9/ubi-minimal:latest --platform=linux/${{ matrix.arch }}
      - name: images
        run: |
          IMAGE_TAG=latest-${{ matrix.arch }} \
          IMAGE_BUILD_EXTRA_FLAGS="--build-arg OS=linux --build-arg ARCH=${{ matrix.arch }}" \
            make -C kueue-addon image
      - name: push
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          docker push quay.io/open-cluster-management/kueue-addon:latest-${{ matrix.arch }}
  image-manifest:
    name: image manifest
    runs-on: ubuntu-latest
    needs: [ images ]
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: create
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login quay.io --username ${{ secrets.DOCKER_USER }} --password-stdin
          # kueue-addon
          docker manifest create quay.io/open-cluster-management/kueue-addon:latest \
            quay.io/open-cluster-management/kueue-addon:latest-amd64 \
            quay.io/open-cluster-management/kueue-addon:latest-arm64
      - name: annotate
        run: |
          # kueue-addon
          docker manifest annotate quay.io/open-cluster-management/kueue-addon:latest \
            quay.io/open-cluster-management/kueue-addon:latest-amd64 --arch amd64
          docker manifest annotate quay.io/open-cluster-management/kueue-addon:latest \
            quay.io/open-cluster-management/kueue-addon:latest-arm64 --arch arm64
      - name: push
        run: |
          docker manifest push quay.io/open-cluster-management/kueue-addon:latest
